# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: npm install

- task: trivy@1
  inputs:
    version: 'latest'
    path: '.'
    exitCode: '0'
- script: ls -lha /tmp/
- script: |
    # Encontrar o arquivo JSON correspondente e renomeá-lo para um nome fixo
    found_file=$(find /tmp -name 'trivy-results-*.json' -print -quit)
    if [ -n "$found_file" ]; then
      echo "Arquivo correspondente encontrado."
      mv "$found_file" /tmp/trivy-results.json
    else
      echo "Nenhum arquivo correspondente encontrado."
      exit 1
    fi
  displayName: 'Encontrar arquivo JSON'
- task: PublishPipelineArtifact@1
  inputs:
      targetPath: '/tmp/trivy-*.json'
      artifact: 'trivy-files'
      publishLocation: 'pipeline'
