name: security-scan

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:                      
    - cron:  '0 3 * * *'         

permissions:                    
  contents: read
  security-events: write        
  id-token: write               

jobs:
  msdo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      
      - name: Run Microsoft Security DevOps
        id: msdo
        uses: microsoft/security-devops-action@v1
        env:          
          GDN_RUN_MINSEVERITY: High
      
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
