name: security-scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
  schedule:                      
    - cron:  '0 3 * * *'         

permissions:                    
  contents: read
  security-events: write        
  id-token: write               

jobs:
  msdo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      
      - name: Run Microsoft Security DevOps
        id: msdo
        uses: microsoft/security-devops-action@v1
        env:          
          GDN_RUN_MINSEVERITY: Warning   
          GDN_RUN_NOBASELINE: true       
      
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
          category: msdo

      - name: Gate por severidade (SARIF)
        run: |
          F="${{ steps.msdo.outputs.sarifFile }}"
          e=$(jq '[.runs[].results[] | select(.level=="error")]   | length' "$F")
          w=$(jq '[.runs[].results[] | select(.level=="warning")] | length' "$F")
          echo "errors=$e warnings=$w"
          # Quebrar com Medium+:
          if [ "$e" -gt 0 ] || [ "$w" -gt 0 ]; then
            echo "Falhando por severidade (Warning+)."
            exit 1
          fi    
